spring.application.name=fisioapp

# Configuración de H2 para que guarde los datos en un archivo local
spring.datasource.url=jdbc:h2:file:./data/fisioappdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Esto crea las tablas automáticamente al arrancar
spring.jpa.hibernate.ddl-auto=update

# Para que podamos ver la base de datos en el navegador (muy útil para el profesor)
spring.h2.console.enabled=true